spring:
  application:
    name: snackcode

  datasource:
    url: jdbc:oracle:thin:@ldwdatabase_high?TNS_ADMIN=/Users/dongwooklee/Downloads/Wallet_ldwdatabase
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: #id
    password: #pw

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect

  thymeleaf:
    prefix: file:/Users/dongwooklee/Documents/myproject/snackcode/src/main/resources/templates/
    #prefix: file:/Users/dongwooklee/Documents/myproject/snackcode/src/main/resources/templates/

    suffix: .html
    cache: false

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

openai:
  model: gpt-3.5-turbo
  api:
    key: #apieky
    url: https://api.openai.com/v1/chat/completions

---
spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:oracle:thin:@ldwdatabase_high?TNS_ADMIN=~/project/Wallet_ldwdatabase

  thymeleaf:
    prefix: classpath:/templates/



