spring:
  application:
    name: snackcode

  datasource:
    url: jdbc:mysql://localhost:3306/snackcode?&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rhcnwkd5%

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

