# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: setup jdk
      uses: actions/setup-java@v4.2.2
      with: 
        distribution: 'temurin'
        java-version: "17"
        
    - name: setup
      run: |
        ls -al
        ./gradlew bootJar

    - name: ftp upload remote server
      uses: milanmk/actions-file-deployer@master
      with:
        remote-host: ${{ secrets.ORACLE_CLOUD_IP }}
        remote-user: ${{ secrets.ORACLE_CLOUD_USER }}
        ssh-private-key: ${{ secrets.ORACLE_CLOUD_KEY }}
        local-path: "./build/libs/"
        remote-path: "/home/ubuntu/project/libs/"
        sync: "full"
      
      # with:
      #   host: ${{ secrets.ORACLE_CLOUD_IP }}
      #   username: ${{ secrets.ORACLE_CLOUD_USER }}
      #   key: ${{ secrets.ORACLE_CLOUD_KEY }}
      #   port: 22
      #   script: |
      #     ~/project/start_codedrawer.sh
          
    
